### ISSUE TITLE
Build with the latest image generates "Operation not permitted" errors in assemble

### ISSUE THREAD

**Issue by tmckayus** [sclorg/s2i-python-container#178] opened 2017-01-27 21:40 UTC
The fix-permissions calls in the assemble script generate warnings on the python files.
 
Here is the command I ran, and the output from the build script (could be any python source):

  oc new-app --name testbuild docker.io/centos/python-27-centos7~https://github.com/tmckayus/play.git

Build logs:

Cloning "https://github.com/tmckayus/play.git" ...
	Commit:	bf8668eef2718c42339bcfae4a42f41a1342f1c2 (Add a spark-conf subdir to play with custom spark config)
	Author:	Trevor McKay <tmckay@redhat.com>
	Date:	Wed Jan 25 11:46:54 2017 -0500

---> Installing application source ...
chgrp: changing group of '/opt/app-root/include/python2.7': Operation not permitted
chgrp: changing group of '/opt/app-root/lib/python2.7/UserDict.py': Operation not permitted
chgrp: changing group of '/opt/app-root/lib/python2.7/_abcoll.py': Operation not permitted
chgrp: changing group of '/opt/app-root/lib/python2.7/_weakrefset.py': Operation not permitted
chgrp: changing group of '/opt/app-root/lib/python2.7/abc.py': Operation not permitted
chgrp: changing group of '/opt/app-root/lib/python2.7/codecs.py': Operation not permitted
chgrp: changing group of '/opt/app-root/lib/python2.7/config': Operation not permitted
chgrp: changing group of '/opt/app-root/lib/python2.7/copy_reg.py': Operation not permitted
chgrp: changing group of '/opt/app-root/lib/python2.7/encodings': Operation not permitted
chgrp: changing group of '/opt/app-root/lib/python2.7/fnmatch.py': Operation not permitted
chgrp: changing group of '/opt/app-root/lib/python2.7/genericpath.py': Operation not permitted
chgrp: changing group of '/opt/app-root/lib/python2.7/lib-dynload': Operation not permitted
chgrp: changing group of '/opt/app-root/lib/python2.7/linecache.py': Operation not permitted
chgrp: changing group of '/opt/app-root/lib/python2.7/locale.py': Operation not permitted
chgrp: changing group of '/opt/app-root/lib/python2.7/ntpath.py': Operation not permitted
chgrp: changing group of '/opt/app-root/lib/python2.7/os.py': Operation not permitted
chgrp: changing group of '/opt/app-root/lib/python2.7/posixpath.py': Operation not permitted
chgrp: changing group of '/opt/app-root/lib/python2.7/re.py': Operation not permitted
chgrp: changing group of '/opt/app-root/lib/python2.7/sre.py': Operation not permitted
chgrp: changing group of '/opt/app-root/lib/python2.7/sre_compile.py': Operation not permitted
chgrp: changing group of '/opt/app-root/lib/python2.7/sre_constants.py': Operation not permitted
chgrp: changing group of '/opt/app-root/lib/python2.7/sre_parse.py': Operation not permitted
chgrp: changing group of '/opt/app-root/lib/python2.7/stat.py': Operation not permitted
chgrp: changing group of '/opt/app-root/lib/python2.7/types.py': Operation not permitted
chgrp: changing group of '/opt/app-root/lib/python2.7/warnings.py': Operation not permitted
chmod: changing permissions of '/opt/app-root/include/python2.7': Operation not permitted
chmod: changing permissions of '/opt/app-root/lib/python2.7/UserDict.py': Operation not permitted
chmod: changing permissions of '/opt/app-root/lib/python2.7/_abcoll.py': Operation not permitted
chmod: changing permissions of '/opt/app-root/lib/python2.7/_weakrefset.py': Operation not permitted
chmod: changing permissions of '/opt/app-root/lib/python2.7/abc.py': Operation not permitted
chmod: changing permissions of '/opt/app-root/lib/python2.7/codecs.py': Operation not permitted
chmod: changing permissions of '/opt/app-root/lib/python2.7/config': Operation not permitted
chmod: changing permissions of '/opt/app-root/lib/python2.7/copy_reg.py': Operation not permitted
chmod: changing permissions of '/opt/app-root/lib/python2.7/encodings': Operation not permitted
chmod: changing permissions of '/opt/app-root/lib/python2.7/fnmatch.py': Operation not permitted
chmod: changing permissions of '/opt/app-root/lib/python2.7/genericpath.py': Operation not permitted
chmod: changing permissions of '/opt/app-root/lib/python2.7/lib-dynload': Operation not permitted
chmod: changing permissions of '/opt/app-root/lib/python2.7/linecache.py': Operation not permitted
chmod: changing permissions of '/opt/app-root/lib/python2.7/locale.py': Operation not permitted
chmod: changing permissions of '/opt/app-root/lib/python2.7/ntpath.py': Operation not permitted
chmod: changing permissions of '/opt/app-root/lib/python2.7/os.py': Operation not permitted
chmod: changing permissions of '/opt/app-root/lib/python2.7/posixpath.py': Operation not permitted
chmod: changing permissions of '/opt/app-root/lib/python2.7/re.py': Operation not permitted
chmod: changing permissions of '/opt/app-root/lib/python2.7/sre.py': Operation not permitted
chmod: changing permissions of '/opt/app-root/lib/python2.7/sre_compile.py': Operation not permitted
chmod: changing permissions of '/opt/app-root/lib/python2.7/sre_constants.py': Operation not permitted
chmod: changing permissions of '/opt/app-root/lib/python2.7/sre_parse.py': Operation not permitted
chmod: changing permissions of '/opt/app-root/lib/python2.7/stat.py': Operation not permitted
chmod: changing permissions of '/opt/app-root/lib/python2.7/types.py': Operation not permitted
chmod: changing permissions of '/opt/app-root/lib/python2.7/warnings.py': Operation not permitted

Pushing image 172.30.100.159:5000/tmckay-test/testbuild:latest ...
Pushed 0/10 layers, 0% complete
Pushed 1/10 layers, 10% complete
Pushed 2/10 layers, 20% complete
Push successful

**Comment by tmckayus** [comment] 2017-01-27 21:44
Hmm, the warnings are mentioned in this PR https://github.com/sclorg/s2i-python-container/pull/159

Has it been decided to leave them?

**Comment by bparees** [comment] 2017-01-27 21:44
@GrahamDumpleton cc

**Comment by GrahamDumpleton** [comment] 2017-01-27 22:03
I already clearly explained the problem in the PR. The warnings are harmless, but are annoying. It is ``fix-permissions`` in the base image which is the problem, as it doesn't cope with the fact one could have symlinks under ``/opt/app-root`` which point outside of that directory. It is outside of my purview to be able to make a decision about whether ``fix-permissions`` should be changed, or the S2I builder changed to not use ``fix-permissions`` and do it in a way that deals with the issue.

**Comment by tmckayus** [comment] 2017-01-27 22:12
thanks Graham.  Should we move the issue to the base image?  I understand that they're harmless, but I also thought this was something I caused in my derived image and I had to convince myself that I wasn't doing anything warning-worthy in my Dockerfile/s2i scripts.  It would be good to spare users the wondering if possible.

**Comment by GrahamDumpleton** [comment] 2017-02-16 07:26
Raised in https://github.com/sclorg/s2i-base-container/issues/112 against base image which includes ``fix-permissions``.

**Comment by rhcarvalho** [comment] 2017-03-28 21:08
@sclorg/container-images any plans to handle this? I also got warned by the many permission errors in my build logs.

**Comment by GrahamDumpleton** [comment] 2017-03-28 22:34
This really needs  a C/go version of fix-permissions that is more intelligent. Ignoring that warning, another problem with fix-permissions is that running chmod/chgrp on files which already have the correct permissions still results in a copy being made into the new layer even though nothing is changed. At least that is what my tests of chmod/chown show.

Here is ``docker history`` on image where same chgrp/chmod was run in two separate builder layers. See how each time layer adds 414MB.

```
7ec941f37ac6        About a minute ago   /bin/sh -c chgrp -Rf root /opt/conda && chmod   414 MB
b00ad8753768        18 hours ago         /bin/sh -c chgrp -Rf root /opt/conda && chmod   414 MB
```

If that is correct, then running fix-permissions on same directory structure, due to incremental additions being made in a derived image, is going to make image bigger than it needs to be.

**Comment by GrahamDumpleton** [comment] 2017-03-29 00:06
When I talk about an intelligent script I mean like this:

```
#!/usr/bin/env python

from __future__ import print_function

import os
import sys
import stat

def fix(path):
    info = os.lstat(path)

    if not stat.S_ISLNK(info.st_mode):
        if info.st_gid != 0:
            print("os.chown(%s, -1, 0)" % path)
            os.chown(path, -1, 0)

        if not (info.st_mode & stat.S_IWGRP):
            print("os.chmod(%s, %d)" % (path, info.st_mode | stat.S_IWGRP))
            os.chmod(path, info.st_mode | stat.S_IWGRP)

for dirpath, dirnames, filenames in os.walk(sys.argv[1]):
    fix(dirpath)

    for filename in filenames:
        fix(os.path.join(dirpath, filename))
```

This doesn't follow symlinks when traversing (default behaviour of os.walk()).

It doesn't attempt to change group or permissions on a symlink.

And doesn't reapply something if the correct value was already present. This ensures don't duplicate file contents in new layer when no change was actually needed.

Using this script above to fix permissions, layers of image if run twice is instead:

```
ce3a693aa15b        5 minutes ago       /bin/sh -c /opt/app-root/fix-permissions /opt   0 B
25d10b3df661        5 minutes ago       /bin/sh -c /opt/app-root/fix-permissions /opt   414 MB
```

As simple as this Python script is, there would be objections to using it because it is Python, even if Python is in base images since OS system Python has to be there for package installers to work. Would also be objections as would not be seen as performant enough.

Anyway, it shows how an intelligent version of fix-permissions would work.

**Comment by andrewklau** [comment] 2017-03-29 01:25
:+1: 

btw cgroup-limits use python https://github.com/sclorg/s2i-base-container/blob/master/bin/cgroup-limits

**Comment by omron93** [comment] 2017-03-30 09:37
@GrahamDumpleton Why not to only change `fix-permissions` script?

```
find $1 -exec chgrp -h 0 {} \;
find $1 \! -type l -exec chmod g+rw {} \;
find $1 -type d -exec chmod g+x {} +
```

**Comment by GrahamDumpleton** [comment] 2017-03-30 09:55
Running chmod/chgrp on a file that existed in a lower layer of the image, even when the permissions are already what is required, results in a new copy of the file being made in the new Docker layer. So it is more than just avoiding changing permissions on a symlink.

Also, from memory ``chgrp -h`` doesn't work on Linux as it doesn't support changing permissions on the symbolic link itself. It will always reflect the permissions of what the symlink points at.

**Comment by omron93** [comment] 2017-03-30 11:01
> Running chmod/chgrp on a file that existed in a lower layer of the image, even when the permissions are already what is required, results in a new copy of the file being made in the new Docker layer. So it is more than just avoiding changing permissions on a symlink.

And this is different with python script?

What files in python case are from previous layer? In `/opt/app-root`?

> Also, from memory chgrp -h doesn't work on Linux as it doesn't support changing permissions on the symbolic link itself. It will always reflect the permissions of what the symlink points at.

It works for me on F25 or CentOS7.

**Comment by GrahamDumpleton** [comment] 2017-03-30 21:03
As to what is in lower layer, the whole Python virtual environment which is used is located under ``/opt/app-root``. This is set up as part of the Python S2I base image. Permissions are then fixed again during the S2I build phase, so it passes over the whole Python virtual environment again. Also can happen where people are creating a custom Python S2I builder image with additional Python packages installed and the ``run`` script replaced. In that case permissions need to be fixed in the ``Dockerfile`` for the custom image after additional packages installed. This last scenario has already been occurring in some of the Spark/Jupyter Notebook work that is happening.

And yes the Python script is different as it checks the group and access permissions and doesn't try and change them if already have desired values. The ``chmod`` command appears to be quite stupid in this respect as it flushes through changes even though nothing has changed resulting in copy of file in new layer.

**Comment by omron93** [comment] 2017-03-31 07:21
> As to what is in lower layer, the whole Python virtual environment which is used is located under /opt/app-root. This is set up as part of the Python S2I base image. Permissions are then fixed again during the S2I build phase, so it passes over the whole Python virtual environment again. Also can happen where people are creating a custom Python S2I builder image with additional Python packages installed and the run script replaced. In that case permissions need to be fixed in the Dockerfile for the custom image after additional packages installed. This last scenario has already been occurring in some of the Spark/Jupyter Notebook work that is happening.

At least
```
RUN source scl_source enable rh-python35 && \
    virtualenv /opt/app-root

RUN chown -R 1001:0 /opt/app-root && chmod -R og+rwx /opt/app-root
```
could be joined to avoid this problem during `docker build`.

> And yes the Python script is different as it checks the group and access permissions and doesn't try and change them if already have desired values. The chmod command appears to be quite stupid in this respect as it flushes through changes even though nothing has changed resulting in copy of file in new layer.

Thanks for explanation. `find` with `\! -gid 0` could solve this.

But I am not against python solution.

**Comment by GrahamDumpleton** [comment] 2017-03-31 07:36
It isn't just what is done in the ``Dockerfile``, although had overlooked that case. It is the ``fix-permissions`` run in the ``assemble`` script as part of S2I build which I was thinking of.

* https://github.com/sclorg/s2i-python-container/blob/master/2.7/s2i/bin/assemble#L61

So the ``Dockerfile`` should perhaps be changed to use ``fix-permissions`` in same ``RUN`` statement. But the ``fix-permissions`` in base image still needs to be fixed.

If the ``\! -gid 0`` can partly solve the issue then great. You can see the current ``fix-permissions`` at:

* https://github.com/sclorg/s2i-base-container/blob/master/bin/fix-permissions

and currently has:

```
chgrp -R 0 $1;
find -L $1 -xtype l -exec chgrp 0 {} \;
chmod -R g+rw $1;
find -L $1 -xtype l -exec chmod g+rw {} \;
find $1 -type d -exec chmod g+x {} +
```

So the recursive ``chgrp`` and ``chmod`` would need to be replaced so is executed by ``find`` with appropriate filter on whether already set.

How though do you avoid running chmod if already has ``g+wx``? Can you use ``\!`` with permission checks?

**Comment by omron93** [comment] 2017-03-31 14:09
> It isn't just what is done in the Dockerfile, although had overlooked that case. It is the fix-permissions run in the assemble script as part of S2I build which I was thinking of.

I know. Only wanted to point to same problem, which won't be fixed by `fix-permission` fix.

> So the recursive chgrp and chmod would need to be replaced so is executed by find with appropriate filter on whether already set.

> How though do you avoid running chmod if already has g+rw for files and g+x for directories? Can you use \! with permission checks?

Yes. It is possible - `\! -perm /g+rw`

I've looked into github history of `fix-permissions` and it was all done by three `find ... -exec` commands , but it was slow (discussed in https://github.com/sclorg/s2i-base-container/issues/108)

**Comment by GrahamDumpleton** [comment] 2017-03-31 20:40
So we get back to whether a custom Go/C application needs to be written to do it. The Python script demonstrates what I think is required, but isn't going to be performant enough. The problem is whether it is going to be too hard to get a custom binary in there since isn't going to be packaged.

**Comment by GrahamDumpleton** [comment] 2017-04-03 02:46
I have posted a summary of all new issues encountered on https://github.com/sclorg/s2i-base-container/issues/112. In addition to problem with copies of files being made in new layer, the existing ``fix-permissions`` doesn't propagate execute bit from user to group for files. This would be a problem where permissions were ``u+rwx,g-rwx``. That is assigned user ID, wouldn't be able to execute program any more. In that other issue I have added example C code of my idea of what ``fix-permissions`` should do.

**Comment by omron93** [comment] 2017-04-03 09:06
> The problem is whether it is going to be too hard to get a custom binary in there since isn't going to be packaged.

Implementation in non-interpreted language would be a big problem IMPOV. It is not good idea to rely on compilation on host, so it should be done in container. And would require a good way how to install compiler and remove it again in Dockerfile `RUN` (without any garbage files).

> So we get back to whether a custom Go/C application needs to be written to do it. The Python script demonstrates what I think is required, but isn't going to be performant enough.

I think there is a bash solution performant enough.

```
#!/bin/sh
# Fix permissions on the given directory to allow group read/write of
# regular files and execute of directories.
find $1 \! -gid 0 -exec chgrp 0 {} +
find $1 \! -perm /g+rw -exec chmod g+rw {} +
find $1 -type d \! -perm /g+x -exec chmod g+x {} +
```

It only checks files which currently don't have proper gid/permissions... `+` in the end runs `chgrp`/`chmod` with more files at once.

@GrahamDumpleton @bparees Please take a look.
(related to https://github.com/sclorg/s2i-base-container/issues/112)

**Comment by GrahamDumpleton** [comment] 2017-04-03 10:26
This doesn't propagate ``u+x``  to group where there is no current ``g+x`` for a file (not a directory). I raised this in https://github.com/sclorg/s2i-base-container/issues/112 as another issue.

As to compiler availability, the s2-base-container image already has gcc installed. So that is not an issue.

**Comment by omron93** [comment] 2017-04-03 11:03
Adding `find $1 -perm /u+x -a \! -perm /g+x -exec chmod g+x {} +` fixes this.

Or if it is not required that directory without `u+x` should get `g+x`, `find $1 -type d \! -perm /g+x -exec chmod g+x {} +` could be replaced by `find $1 -perm /u+x -a \! -perm /g+x -exec chmod g+x {} +`

**Comment by omron93** [comment] 2017-04-03 11:40
> As to compiler availability, the s2-base-container image already has gcc installed. So that is not an issue.

I didn't know it. Thanks.

> Also, are those commands alone going to update permission on target of symlink when pointing at a file?

Yes, they are.

But not sure how the script should behave:
- if a file is a symlink to a file -> change owner and permissions of target file
- if a file is a symlink to a directory (even outside of `$1` dir) -> check all files in target directory and change owner and permissions of them
(symlinks in Linux are always accessible by everyone, so it is not needed to change properties of link itself)

To comply also with the second point:
```
find -L $1 \! -gid 0 -exec chgrp 0 {} +
find -L $1 \! -perm /g+rw -exec chmod g+rw {} +
#find -L $1 -perm /u+x -a \! -perm /g+x -exec chmod g+x {} +
find -L $1 -type d \! -perm /g+x -exec chmod g+x {} +
```

**Comment by GrahamDumpleton** [comment] 2017-04-03 12:28
From what I understood from what was said in https://github.com/sclorg/s2i-base-container/issues/112 you only treated a symlink to a file as special and updated target file permissions. If symlink was to a directory, you didn't traverse into it or touch anything in the directory it referred to.

**Comment by bparees** [comment] 2017-04-03 14:01
> From what I understood from what was said in sclorg/s2i-base-container#112 you only treated a symlink to a file as special and updated target file permissions. If symlink was to a directory, you didn't traverse into it or touch anything in the directory it referred to.

i don't think the intent of the fix was to make a distinction between directory symlinks and file symlinks, but i'd have to go test the chmod vs find behavior to see how each behaves when the symlinks points to a directory.

my only point would be that whatever changes are being made here should preserve the existing behavior with respect to symlinks.  If that means only treating symlinks to files as special, that's fine, but we first need to confirm the existing behavior is not following symlinks into directories.

**Comment by omron93** [comment] 2017-04-04 06:42
> my only point would be that whatever changes are being made here should preserve the existing behavior with respect to symlinks.

So what is a current expected behavior?

If argument to `fix-permissions` is:
1. file -> change permissions of file
2. symlink to file -> change permissions of target file
3. directory -> "recursively run itself" on all items in this directory (skip symlinks to directories) according to points 1.-3. 
4. symlink to directory -> get target directory of a symlink and operate with it as in point 3.

@bparees Right?

Skip symlinks to directories entirely or change permissions of target directory but don't operate on items in it?

**Comment by GrahamDumpleton** [comment] 2017-04-04 06:56
Having to focus on other stuff right now, but one point I will make about following symlinks pointing at directories, is that if you do that recursively, you could end up in a never ending loop if you are not careful, were a subsequent symlink pointed back to a directory hierarchy you had already visited.

**Comment by bparees** [comment] 2017-04-04 14:03
> So what is a current expected behavior?

the current behavior *is* the expected behavior.  we can certainly entertain arguments (such as @GrahamDumpleton's point about potential recursive loops) for changing it, but the starting point should be to understand and match the current behavior.

**Comment by omron93** [comment] 2017-04-05 08:44
> the current behavior is the expected behavior. we can certainly entertain arguments (such as @GrahamDumpleton's point about potential recursive loops) for changing it, but the starting point should be to understand and match the current behavior.

I want to know if "the current behavior" can be somehow described? (how it should work)

Or if it is only "what is in the code" is what we want...

**Comment by bparees** [comment] 2017-04-05 13:11
The current behavior:

1) recursively chmods/chgrps all files/dirs in the provided path.  symlinks are effectively ignored (thus as are the targets of those symlinks)
2) all symlinks are followed to their target(whether a directory or a file) and a non-recursive chmod/chgrp is performed on them.

so give a dir "/tmp/foo" containing "/tmp/foo/file1" and a symlink "b" that points to /tmp/foo, with this logic, /tmp/foo will be modifed, /tmp/fool/file1 will not be modified.

the good news is that means no recursive symlink loops.  the bad news is it's probably not really correct in that /tmp/foo/file1 probably should be modified, if we're trying to be at all consistent (perhaps don't follow it if it's a symlink, but at least modify it).  (in otherwords, step 2 should follow the symlink and invoke a recursive chmod/chgrp on the target.  since recursive chmod/chgrp doesn't follow symlinks, this is safe from an infinite loop perspective).

**Comment by GrahamDumpleton** [comment] 2017-04-07 05:45
Can we continue the discussion on https://github.com/sclorg/s2i-python-container/issues/178 which is where I have been putting the C code version of what could replace all the ``find`` commands. It also has to be fixed in that base image and better discussion moved there.

**Comment by torsava** [comment] 2017-04-24 08:25
Discussion continues in sclorg/s2i-base-container#112.

**Comment by thesteve0** [comment] 2017-06-13 01:38
Why is this still not fixed? This showed up on the keynote stage for summit. It shows up in all my workshops. 
1) I have to explain to the class this is a problem with our SCL image not their code
2) It makes us look like amateurs. 

I don't understand how this can be allowed to persist for so long

I am going to move this complain to all being in the mentioned discussion. 

I know I have not added anything technically but the fact that this remains unfixed is really causing problems for all public facing work when we try to show how great S2I is for python (and other) devs.

**Comment by andrewklau** [comment] 2017-06-14 07:22
Wouldn't the simple fix be just to include `umask 002` ? At least that has been working for my s2i builders

**Comment by GrahamDumpleton** [comment] 2017-06-14 07:28
Unfortunately setting umask doesn't always work. The problem is packages that like to set specific permissions and don't just inherit the prevailing umask. There also isn't a way to set global umask which applies to all commands run from a Dockerfile.

**Comment by andrewklau** [comment] 2017-06-14 07:47
Do you have an example package that has this problem?

**Comment by GrahamDumpleton** [comment] 2017-06-14 07:50
My experience with problems resolve more around packages installed using a configure/make/make install build method. So I can't recollect issue with specific Python packages. I am looking at bigger picture and considering that people may override/extend the S2I assemble/run scripts to install extra stuff.

**Comment by GrahamDumpleton** [comment] 2017-09-21 10:12
This issue should be able to be closed now as original reported problem was addressed in base image after being raised in https://github.com/sclorg/s2i-base-container/issues/112

**Closed** 2017-10-02 15:04 UTC

**Comment by torsava** [comment] 2017-10-02 15:18
Verified, closed.
