### ISSUE TITLE
Set max version of pipenv in python2.7

### ISSUE THREAD

**Issue by gardar** [sclorg/s2i-python-container#497] opened 2022-02-14 17:12 UTC
Using the latest version of pipenv in python2.7 gives this error:

`ImportError: No module named weakref`

I suggest adding a max or default version of pipenv in python2.7 as pipenv has dropped support for python2 in the latest releases.

https://github.com/pypa/pipenv/issues/4834

`PIN_PIPENV_VERSION=2021.5.29`

**Comment by frenzymadness** [comment] 2022-02-15 06:28
Hello.

Thanks a lot for the report and the PR! However, I don't understand its purpose. Pipenv should have Python 2 compatibility in its metadata and pip in Python 2 environment should install the latest supported version not the latest pipevn release.

* v2021.5.29 - supports Python 2
* v2021.11.5 - yanked
* v2021.11.5.post0 - yanked
* v2021.11.9 - This release and newer are Python 3 only

If I try `pip install pipenv` in Python 2 environment I get the expected version pipenv-2021.5.29. If I try to specify a newer release which does not support Python 2, pip gives me this error because manually selected release is not in a list of available releases:
```
ERROR: Could not find a version that satisfies the requirement pipenv==2021.11.9 (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.1.10, 0.1.11, 0.1.12, 0.1.13, 0.1.14, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.2.7, 0.2.8, 3.0.0, 3.0.1, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.1.4, 3.1.6, 3.1.7, 3.1.8, 3.1.9, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 3.2.4, 3.2.5, 3.2.6, 3.2.7, 3.2.8, 3.2.9, 3.2.10, 3.2.11, 3.2.14, 3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.3.4, 3.3.5, 3.3.6, 3.4.0, 3.4.1, 3.4.2, 3.5.0, 3.5.1, 3.5.2, 3.5.3, 3.5.4, 3.5.5, 3.5.6, 3.6.0, 3.6.1, 3.6.2, 4.0.0, 4.0.1, 4.1.0, 4.1.1, 4.1.2, 4.1.3, 4.1.4, 5.0.0, 5.1.0, 5.1.1, 5.1.2, 5.2.0, 5.3.0, 5.3.1, 5.3.2, 5.3.3, 5.3.4, 5.3.5, 5.4.0, 5.4.1, 5.4.2, 6.0.0, 6.0.1, 6.0.2, 6.0.3, 6.1.0, 6.1.1, 6.1.2, 6.1.3, 6.1.4, 6.1.5, 6.1.6, 6.2.0, 6.2.1, 6.2.2, 6.2.3, 6.2.4, 6.2.5, 6.2.6, 6.2.7, 6.2.8, 6.2.9, 7.0.0, 7.0.1, 7.0.2, 7.0.3, 7.0.4, 7.0.5, 7.0.6, 7.1.0, 7.1.1, 7.2.0, 7.2.1, 7.2.2, 7.2.3, 7.2.4, 7.2.5, 7.2.6, 7.2.7, 7.2.8, 7.2.9, 7.3.0, 7.3.1, 7.3.2, 7.3.3, 7.3.4, 7.3.5, 7.3.6, 7.3.7, 7.3.8, 7.3.9, 7.4.0, 7.4.1, 7.4.2, 7.4.3, 7.4.4, 7.4.5, 7.4.6, 7.4.8, 7.4.9, 7.5.1, 7.6.0, 7.6.1, 7.6.2, 7.6.3, 7.6.4, 7.6.5, 7.6.6, 7.6.7, 7.6.8, 7.6.9, 7.7.0, 7.7.2, 7.7.3, 7.7.4, 7.7.5, 7.7.6, 7.7.7, 7.7.8, 7.7.9, 7.8.0, 7.8.1, 7.8.2, 7.8.3, 7.8.4, 7.8.5, 7.8.6, 7.8.7, 7.8.8, 7.8.9, 7.9.0, 7.9.1, 7.9.2, 7.9.3, 7.9.4, 7.9.5, 7.9.6, 7.9.7, 7.9.8, 7.9.10, 8.0.0, 8.0.1, 8.0.2, 8.0.3, 8.0.4, 8.0.5, 8.0.6, 8.0.7, 8.0.8, 8.1.0, 8.1.1, 8.1.2, 8.1.3, 8.1.4, 8.1.5, 8.1.6, 8.1.7, 8.1.8, 8.1.9, 8.2.0, 8.2.1, 8.2.2, 8.2.3, 8.2.4, 8.2.5, 8.2.6, 8.2.7, 8.3.0, 8.3.1, 8.3.2, 9.0.0, 9.0.1, 9.0.2, 9.0.3, 9.1.0, 10.0.0, 10.0.1, 10.1.0, 10.1.1, 10.1.2, 11.0.0, 11.0.1, 11.0.2, 11.1.0, 11.1.1, 11.1.2, 11.1.3, 11.1.4, 11.1.5, 11.1.6, 11.1.7, 11.1.8, 11.1.9, 11.1.10, 11.1.11, 11.2.0, 11.2.1, 11.2.2, 11.3.0, 11.3.1, 11.3.2, 11.3.3, 11.4.0, 11.5.0, 11.5.1, 11.5.2, 11.5.3, 11.6.0, 11.6.1, 11.6.2, 11.6.3, 11.6.4, 11.6.5, 11.6.7, 11.6.8, 11.6.9, 11.7.0, 11.7.1, 11.7.2, 11.7.3, 11.7.4, 11.8.0, 11.8.2, 11.8.3, 11.9.0, 11.10.0, 11.10.1.dev1, 11.10.1.dev2, 11.10.1.dev3, 11.10.1.dev4, 11.10.1.dev5, 11.10.1, 11.10.2, 11.10.3, 11.10.4, 2018.5.18, 2018.6.25, 2018.7.1, 2018.10.9, 2018.10.13, 2018.11.14, 2018.11.26, 2020.4.1b1, 2020.4.1b2, 2020.5.28, 2020.6.2, 2020.8.13, 2020.11.4, 2020.11.15, 2021.5.29, 2021.11.5)
ERROR: No matching distribution found for pipenv==2021.11.9
```

**Comment by gardar** [comment] 2022-02-15 11:15
Hi, yes I was a bit surprised that a incompatible version was pulled in my build and apparently it's attempting to install v2021.11.5

Here are some parts of the logs that are relative:

```
Successfully installed pip-20.3.4
---> Installing pipenv packaging tool ...
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.

...

Successfully built scandir
Installing collected packages: six, scandir, pathlib2, filelock, distlib, contextlib2, zipp, configparser, importlib-metadata, typing, singledispatch, importlib-resources, platformdirs, virtualenv
Successfully installed configparser-4.0.2 contextlib2-0.6.0.post1 distlib-0.3.3 filelock-3.2.1 importlib-metadata-2.1.3 importlib-resources-3.3.1 pathlib2-2.3.6 platformdirs-2.0.2 scandir-1.10.0 singledispatch-3.7.0 six-1.16.0 typing-3.10.0.0 virtualenv-20.13.0 zipp-1.2.0
New python executable in /opt/app-root/src/.local/venvs/pipenv/bin/python2
Also creating executable in /opt/app-root/src/.local/venvs/pipenv/bin/python
Installing setuptools, pip, wheel...done.
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Looking in indexes: https://<REMOVED>/simple
Collecting pipenv
  Downloading https://<REMOVED>/packages/18/f4/5521af7b82f0b6ed66b4a4eeba8dc2d5ed1e47532041e34a9617328b2e7f/pipenv-2021.11.5-py2.py3-none-any.whl (3.9 MB)
Collecting certifi
  Downloading https://<REMOVED>/packages/37/45/946c02767aabb873146011e665728b680884cd8fe70dde973c640e45b775/certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
Requirement already satisfied, skipping upgrade: setuptools>=36.2.1 in ./.local/venvs/pipenv/lib/python2.7/site-packages (from pipenv) (44.1.1)
Requirement already satisfied, skipping upgrade: pip>=18.0 in ./.local/venvs/pipenv/lib/python2.7/site-packages (from pipenv) (20.3.4)
Collecting virtualenv

...

Installing collected packages: certifi, six, scandir, pathlib2, filelock, distlib, contextlib2, zipp, configparser, importlib-metadata, typing, singledispatch, importlib-resources, platformdirs, virtualenv, virtualenv-clone, pipenv
Successfully installed certifi-2021.10.8 configparser-4.0.2 contextlib2-0.6.0.post1 distlib-0.3.3 filelock-3.2.1 importlib-metadata-2.1.3 importlib-resources-3.3.1 pathlib2-2.3.6 pipenv-2021.11.5 platformdirs-2.0.2 scandir-1.10.0 singledispatch-3.7.0 six-1.16.0 typing-3.10.0.0 virtualenv-20.13.0 virtualenv-clone-0.5.7 zipp-1.2.0
---> Installing dependencies via pipenv ...
Traceback (most recent call last):
  File "/opt/app-root/src/.local/bin/pipenv", line 5, in <module>
    from pipenv import cli
  File "/opt/app-root/src/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/__init__.py", line 22, in <module>
    from pipenv.vendor.vistir.compat import ResourceWarning, fs_str
  File "/opt/app-root/src/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/vendor/vistir/__init__.py", line 4, in <module>
    from .compat import (
  File "/opt/app-root/src/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/vendor/vistir/compat.py", line 13, in <module>
    from .backports.tempfile import NamedTemporaryFile as _NamedTemporaryFile
  File "/opt/app-root/src/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/vendor/vistir/backports/__init__.py", line 6, in <module>
    from .tempfile import NamedTemporaryFile
  File "/opt/app-root/src/.local/venvs/pipenv/lib/python2.7/site-packages/pipenv/vendor/vistir/backports/tempfile.py", line 15, in <module>
    from backports.weakref import finalize
ImportError: No module named weakref
```

Perhaps it's an issue with the pip index that's not reflecting the yanked releases.

**Comment by frenzymadness** [comment] 2022-02-16 09:47
Do you have a project I can use to reproduce the issue? It seems to me that the latest pip with support for Python 2 supports also yanked releases:
```
$ pip install -U pip
…
Successfully installed pip-20.3.4

$ pip install --no-cache-dir pipenv
…
Successfully installed certifi-2021.10.8 configparser-4.0.2 contextlib2-0.6.0.post1 distlib-0.3.4 enum34-1.1.10 filelock-3.2.1 importlib-metadata-2.1.3 importlib-resources-3.3.1 pathlib2-2.3.7.post1 **pipenv-2021.5.29** platformdirs-2.0.2 scandir-1.10.0 singledispatch-3.7.0 six-1.16.0 typing-3.10.0.0 virtualenv-20.13.1 virtualenv-clone-0.5.7 zipp-1.2.0
```
I'm testing this on Fedora. What platform do you use?

**Comment by gardar** [comment] 2022-02-16 15:59
I'm building with podman (buildah) on rhel 8.5.
It's a project that's in a locked down environment so I'm afraid I don't have a project that I can publish to reproduce the issue.

I'm wondering if perhaps the internal pip mirror doesn't support yanking, do you know if I can query the pip mirror somehow to see if it's been yanked?

**Comment by frenzymadness** [comment] 2022-02-17 13:11
It's hard to say for your specific case but PyPI index produces the list of the available packages as an HTML page, for example https://pypi.org/simple/pipenv/
If you inspect the source code, you see that some of the anchors have `data-yanked=""` attribute which marks the yanked releases.
However, PEP 503 says nothing about yanked releases: https://www.python.org/dev/peps/pep-0503/

**Comment by frenzymadness** [comment] 2022-02-17 13:16
Ah, there is a separate PEP for that: https://www.python.org/dev/peps/pep-0592/ What software do you use as the repository?

**Comment by frenzymadness** [comment] 2022-04-25 13:01
Is there anything new about this issue? Does your internal repo support yanked releases? Is there anything I can help you with?

**Comment by gardar** [comment] 2022-04-25 13:13
No nothing new, the internal repo apparently didn't yank it automatically so we had to do it manually.
Not sure if #498 should be merged or not, since it's apparently just a workaround for a bug (or a lack of a feature) in the repo syncing tool.
But I guess it wouldn't hurt to merge it since others might be affected and it's not like it's a majorly invasive code change.

**Comment by frenzymadness** [comment] 2022-04-25 13:46
On the other hand, your PR reimplements the logic PyPI and pip already have and our container images install the correct version of pipenv for Python 2.7 as it is. It's not only about pipenv but if your tools don't support yanking of releases you might hit a similar issue with other packages as well and I think that it's not a good idea to fix the problem here in the container image.

I'll close this issue and linked PR for now.

**Closed by frenzymadness** 2022-04-25 13:46 UTC
